; ABOUT:    MyScript v0.0
; SOURCE:   Ahkv1 A_AhkUser https://www.autohotkey.com/boards/viewtopic.php?t=30038
; LICENSE:  The Unlicense, see https://unlicense.org

/*
    TODO:
*/

#Requires AutoHotkey v2.0+
#SingleInstance Force
#NoTrayIcon

; --- User Configuration ---
TargetTitle := "Message Received!"  ; The title of the receiver's MsgBox/TrayTip (use a unique title if possible)
WM_CUSTOM_STRING_ID := 0            ; Must be set to the ID generated by the receiver!
StringToSend := "Hello from the Sender Script! Time: " . A_Now
; --------------------------

; --- 1. Find the target window's HWND ---
TargetHwnd := WinExist(TargetTitle)

if TargetHwnd = 0
{
    MsgBox("Error: Target script window ('" . TargetTitle . "') not found. Aborting.", "Error", "IconX")
    ExitApp
}

; --- 2. Get the Message ID from the receiver's script (Manual Step for Testing) ---
; In a real application, you might use a known constant ID instead of RegisterWindowMessage,
; but for testing, you need to read the ID from the receiver's tray tip or log.
; FOR DEMO: Assume the receiver's ID is 49152 (a common starting point for dynamic IDs)
WM_CUSTOM_STRING_ID := 49152 
; You should manually read the ID from the Target Script's tray tip and update this value!

; --- 3. Prepare the String Buffer ---
; Determine the size needed for the string in bytes (including null terminator).
; StrPut returns the number of bytes required for the string plus null terminator.
BufferSize := StrPut(StringToSend, "UTF-16") 
;StringLength := BufferSize - 1 ; Length in chars (or bytes if single-byte encoding)
StringLength := StrLen(StringToSend)

; Create a temporary Buffer to hold the string
DataBuf := Buffer(BufferSize, 0)

; Write the string into the Buffer
;StrPut(StringToSend, DataBuf, BufferSize, "UTF-8")
StrPut(StringToSend, DataBuf, BufferSize, "UTF-16")

; --- 4. Send the Message ---
; wparam: The address of the string buffer (DataBuf.Ptr)
; lparam: The length of the string (StringLength)
Result := SendMessage(WM_CUSTOM_STRING_ID, DataBuf.Ptr, StringLength, TargetHwnd)

if Result = ""
{
    MsgBox("Message sent successfully! Check the receiver script's MsgBox.", "Success")
}
else
{
    MsgBox("SendMessage failed or returned an error. Result: " . Result, "Error", "IconX")
}

; Note: The memory in DataBuf remains valid only for the duration of the SendMessage call.
; The receiver must copy the string before the sender's thread moves on.