#Requires AutoHotkey v2.0

#Include <RunAsAdmin>


; --- SETUP COM SECURITY ---
; This allows other processes (even non-admin) to call into this script.
; RPC_C_AUTHN_LEVEL_DEFAULT = 0, RPC_C_IMP_LEVEL_IDENTIFY = 2
; EOAC_NONE = 0
DllCall("ole32\CoInitializeSecurity", 
    "Ptr", 0, "Int", -1, "Ptr", 0, "Ptr", 0, 
    "UInt", 1, "UInt", 3, "Ptr", 0, "UInt", 0x1000, "Ptr", 0)

; Create a simple object to share
MyObject := { 
    Message: "Hello from Admin!",
    Add: (this, a, b) => a + b 
}

; Register the object with a unique GUID (generated by you)
; Using the IDispatch interface (IID_IDispatch)

CLSID := "{2F6D1410-B14D-4F71-A2A2-B67D3D22467D}" ; Change this to your own GUID

;IID_IDispatch := "{00020400-0000-0000-C000-000000000046}"

; Get the raw pointer to the object's IDispatch interface
; global GlobalWrapper := ComValue(9, MyObject) 
; pDispatch := ComObjValue(GlobalWrapper)

; Register it in the Running Object Table (ROT)
; 0 = ACTIVEOBJECT_STRONG
; res := DllCall("oleaut32\RegisterActiveObject", 
;     "Ptr", pDispatch, 
;     "Ptr", Buffer(16, 0).Ptr && DllCall("ole32\CLSIDFromString", "Str", CLSID, "Ptr", Buffer(16, 0).Ptr) ? Buffer(16, 0).Ptr : Buffer(16, 0).Ptr,
;     "UInt", 0, 
;     "UIntP", &hCookie := 0)

hCookie:= ObjRegisterActive(MyObject, CLSID)

MsgBox("Registered! Cookie: " hCookie "`nWaiting for User access...")

try {
    ; Access the object from the ROT
    RemoteObj := ComObjActive(CLSID)
    
    MsgBox("Successfully connected!`n" 
           "Message: " RemoteObj.Message "`n"
           "Calculation (5+5): " RemoteObj.Add(5, 5))
} catch {
    MsgBox("Failed to connect. Is the Admin script running?")
}

; Keep script alive
;Persistent()
ExitApp

OnExit((*) => DllCall("oleaut32\RevokeActiveObject", "UInt", hCookie, "Ptr", 0))

ObjRegisterActive(obj, CLSID, Flags:=0) {
    static cookieJar := Map()
    if (!CLSID) {
        if (cookie := cookieJar.Delete(obj)) != ""
            DllCall("oleaut32\RevokeActiveObject", "uint", cookie, "ptr", 0)
        return
    }
    if cookieJar.Has(obj)
        throw Error("Object is already registered", -1)
    _clsid := Buffer(16, 0)
    if (hr := DllCall("ole32\CLSIDFromString", "wstr", CLSID, "ptr", _clsid)) < 0
        throw Error("Invalid CLSID", -1, CLSID)
    hr := DllCall("oleaut32\RegisterActiveObject", "ptr", ObjPtr(obj), "ptr", _clsid, "uint", Flags, "uint*", &cookie:=0, "uint")
    if hr < 0
        throw Error(format("Error 0x{:x}", hr), -1)
    cookieJar[obj] := cookie
    return hr
}